Rails:
  Enabled: true

# Multi-line method chaining should be done with trailing dots.
Style/DotPosition:
  EnforcedStyle: trailing

HashSyntax:
  EnforcedStyle: hash_rockets
  SupportedStyles:
    - ruby19
    - hash_rockets

# Override HoundCI's preference for double quotes:
Style/StringLiterals:
  EnforcedStyle: single_quotes

# Would enforce "-> { }", which we cannot use yet.
Lambda:
  Enabled: false

# ...
LineLength:
  Max: 99

# Relax some of the cops for tests
Metrics/ClassLength:
  Exclude:
    - test/**/*.rb
Metrics/MethodLength:
  Exclude:
    - test/**/*.rb
