language: ruby

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1
  - 2.2

gemfile:
  - gemfiles/Gemfile.rails32
  - gemfiles/Gemfile.rails41
  - gemfiles/Gemfile.rails42

sudo: false

cache: bundler

before_install: "rm ${BUNDLE_GEMFILE}.lock"

before_script: "bundle update"

script: "bundle exec rake test"
