language: ruby

rvm:
  - 2.1
  - 2.2
  - 2.3

gemfile:
  - gemfiles/Gemfile.rails32
  - gemfiles/Gemfile.rails41
  - gemfiles/Gemfile.rails42

sudo: false

cache: bundler

before_script: "bundle update"

script: "bundle exec rake test"
