language: ruby

rvm:
  - 2.3.6
  - 2.4.3
  - 2.5.0

gemfile:
  - gemfiles/Gemfile.rails42
  - gemfiles/Gemfile.rails50
  - gemfiles/Gemfile.rails51

sudo: false

cache: bundler

before_script: "bundle update"

script: "bundle exec rake test"
