name: Lint

on: [pull_request]

jobs:
  rubocop:
    name: RuboCop

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # actions/checkout@v6 see https://github.com/actions/checkout/releases/tag/v6
      with:
        fetch-depth: 0 # fetch everything
    - name: Set up Ruby
      uses: ruby/setup-ruby@0cb964fd540e0a24c900370abf38a33466142735 # ruby/setup-ruby@v1 see https://github.com/ruby/setup-ruby/tree/v1
      with:
        ruby-version: 3.3
    - name: Install dependencies
      run: bundle install
    - name: Run RuboCop against BASE..HEAD changes
      run: bundle exec rake rubocop:diff origin/${GITHUB_BASE_REF#*/}

