name: Lint

on: [pull_request]

jobs:
  rubocop:
    name: RuboCop

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # actions/checkout@v6 see https://github.com/actions/checkout/releases/tag/v6
      with:
        fetch-depth: 0 # fetch everything
    - name: Set up Ruby
      uses: ruby/setup-ruby@0dafeac902942906541bc140009cdbf32665b601 # ruby/setup-ruby@v1 see https://github.com/ruby/setup-ruby/tree/v1
      with:
        ruby-version: 4.0
    - name: Install dependencies
      run: bundle install
    - name: Run RuboCop against BASE..HEAD changes
      run: bundle exec rake rubocop:diff origin/${GITHUB_BASE_REF#*/}

